var outfit = [ 
            "<div id='proGirl' class='outfits'><div id='blouse' class='innerHover'><div id='blousepop' class='popupdiv'>A nice blouse or button up gives you a clean, polished look. It&#39;ll show that you know how to dress for the job you want.</div></div><div id='pants' class='innerHover'><div id='pantspop' class='popupdiv'>A pencil skirt compliments the top well and is a classic professional look. It can be substituted with dress slacks.</div></div><div id='shoes' class='innerHover'><div id='shoespop' class='popupdiv'>Wear short, work-appropriate heels or flats that are neutral colors like black or dark brown.</div></div></div><div id='proGuy' class='outfits'><div id='blazer' class='innerHover'><div id='blazerpop' class='popupdiv'>A blazer compliments the shirt and tie and helps you look more professional. It&#39;ll help give you the right first impression.</div></div><div id='dressShirt' class='innerHover'><div id='dressShirtpop' class='popupdiv'>A button down shirt is completed with a tie and makes you look ready for any job.</div></div><div id='pants' class='innerHover'><div id='pantspop' class='popupdiv'>Wear nice slacks that match your blazer to have a cohesive look.</div></div><div id='shoes' class='innerHover'><div id='shoespop' class='popupdiv'>Any dress shoes will work as long as they are black or dark brown.</div></div></div>", 
            "<div id='bcGirl' class='outfits'><div id='dress' class='innerHover'><div id='dresspop' class='popupdiv'>You can never go wrong with a nice solid color dress. It&#39;s comfortable and professional.</div></div><div id='stockings' class='innerHover'><div id='stockingspop' class='popupdiv'>Wear stockings to up the professional look of your dress.</div></div><div id='shoes' class='innerHover'><div id='shoespop' class='popupdiv'>Most shoes that aren&#39;t flip flops or sneakers will pass in a business casual look.</div></div></div><div id='bcGuy' class='outfits'><div id='butUp' class='innerHover'><div id='butUppop' class='popupdiv'>Polo shirts or button down tops without a tie help keep the professional look without being too overdone.</div></div><div id='pants' class='innerHover'><div id='pantspop' class='popupdiv'>Slacks or dark colored pants compliment your top while keeping you looking professional.</div></div><div id='shoes' class='innerHover'><div id='shoespop' class='popupdiv'>Wear nice dress shoes or plain colored boots or slip ons to stay looking professional.</div></div></div>", 
            "<div id='casGirl' class='outfits'><div id='butUp' class='innerHover'><div id='butUppop' class='popupdiv'>A tank top is too casual to wear to an interview. There&#39;s nothing wrong with it, but you want to look more polished for your first impression.</div></div><div id='pants' class='innerHover'><div id='pantspop' class='popupdiv'>Light colored jeans, jeans with holes, or sweatpants should be avoided in interviews.</div></div><div id='shoesCG' class='innerHover'><div id='shoespop' class='popupdiv'>Avoid wearing sneakers to show your employer you care from head to toe.</div></div></div><div id='casGuy' class='outfits'><div id='butUp' class='innerHover'><div id='butUppop' class='popupdiv'>Try not to wear graphic tees to interviews, since they&#39;re too casual and not polished.</div></div><div id='pants' class='innerHover'><div id='pantspop' class='popupdiv'>Don&#39;t wear jeans that are light in color, blue, or have holes in them.</div></div><div id='shoes' class='innerHover'><div id='shoespop' class='popupdiv'>Don&#39;t wear sneakers to an interview in order to avoid a messy look.</div></div></div>" ];
var outfitContainer = document.getElementById("outfitContainer");
var changeOutfit = document.getElementById("changeoutfit");
function changeFunction(i){
    outfitContainer.innerHTML = outfit[i];
}
changeFunction(0);